spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpra0797/config-server
          search-paths:          - Configuracion
          
server :
  port : 8081
  
