server:
      port: 9090
      
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    producto:
      path: /items/**
      service-id: producto-ms
    almacen:
      path: /almacen/**
      service-id: almacen-ms
    ordenes:
      path: /ordenes/**
      service-id: ordenes-ms
    compania:
      path: /compania/**
      service-id: compania-ns
                  
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}      